image: docker:latest

services:
  - docker:dind

stages:
  - lint
  - build

lint-backend:
  stage: lint
  before_script:
    - apk add --update nodejs nodejs-npm
  script:
    - cd backend
    - npm install
    - npm run lint:ci

lint-frontend:
  stage: lint
  before_script:
    - apk add --update nodejs nodejs-npm
  script:
    - cd frontend
    - npm install
    - npm run lint:ci

build-image:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
  script:
    - docker build -t bacali95/personal-website:latest .
    - docker push bacali95/personal-website:latest
  only:
    - master
  when: manual
