# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

variables:
  CI_REGISTRY: https://docker.nasreddinebacali.info

services:
  - docker:dind
 
stages:
  - Build and push backend image
  - Build and push frontend image

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build-backend:
  stage: Build and push backend image
  script:
    - docker build -t "$CI_REGISTRY/personal-website-backend:latest" .
    - docker push "$CI_REGISTRY/personal-website-backend:latest"
  only:
    - master

build-frontend:
  stage: Build and push frontend image
  script:
    - docker build -t "$CI_REGISTRY/personal-website-frontend:latest" .
    - docker push "$CI_REGISTRY/personal-website-frontend:latest"
  only:
    - master