image: docker:latest

services:
  - docker:dind

stages:
  - build

build-image:
  stage: build
  before_script:
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" --password-stdin
  script:
    - docker build -t bacali95/personal-website:latest .
    - docker push bacali95/personal-website:latest
  only:
    - master
  when: manual
