version: "3"

services:
  www:
    image: registry.gitlab.com/bacali/personal-website/entrypoint:latest
    ports:
      - 4000:4000
    links:
      - backend:backend
      - frontend:frontend
  frontend:
    image: registry.gitlab.com/bacali/personal-website/frontend:latest
  backend:
    image: registry.gitlab.com/bacali/personal-website/backend:latest
    environment:
      - ENV=test
      - ADMIN_USERNAME=username
      - ADMIN_PASSWORD=password
      - DATABASE_HOST=mongodb_hostname
      - DATABASE_USER=mongodb_username
      - DATABASE_PASS=mongodb_password
      - DATABASE_NAME=mongodb_database_name
      - IMAGE_API_KEY=cloudinary_api_key
      - IMAGE_API_SECRET=cloudinary_api_secret
      - IMAGE_CLOUD_NAME=cloudinary_cloud_name
      - TINIFY_API_KEY=tinify_api_key
